### ISSUE TITLE
Says "no readme"

### ISSUE THREAD

**Issue by pawamoy** [Xe/praise-me#2]
Nice project, thanks!

I tried it twice on my profile, and both times it said I didn't have a readme, but I do.

**Comment by Xe** [comment]
Try again, you may get lucky and hit an instance that doesn't have it cached. I had to scale things in a hurry, so the cache is super fucked.

**Comment by pawamoy** [comment]
That makes sense, thanks! I think we can close this then :)

**Comment by Xe** [comment]
It's just an AI praise gacha pull!
