### ISSUE TITLE
Caching of results causing incorrect praises to be delivered

### ISSUE THREAD

**Issue by Mohit-1** [Xe/praise-me#4]
I generated a praise for my profile when I had 1 follower. The generated text was appropriate and nice.
However, in some time I gained a new follower, and while generating the praise again, it still shows the older text. There seems to be a cache implemented at the username level.

We can add a logic in the backend to check if there has been a significant change in the user's profile, and bypass the cache if it's true.

**Comment by Xe** [comment]
This is a feature to reduce API rate limit load.
