### ISSUE TITLE
Praise doesn't distinguish between source and forked repostiories

### ISSUE THREAD

**Issue by miketheman** [Xe/praise-me#6]
https://github.com/Xe/praise-me/blob/c2b09ce7d0325f048de07a3df07287686a09bc93/routes/api/praise/%5Bname%5D.ts#L85-L106

Either filter out forks from the API call, or add source/fork as a property and handle those instead

**Comment by sntxrr** [comment]
This would be a really nice feature. Overall fantastic work @Xe ❤️
